async function auth(){const r=await fetch("/api/admin/me",{credentials:"include",cache:"no-store"});if(!r.ok){location.replace("/admin/login.html");return false}document.getElementById("panel").hidden=false;document.getElementById("authMsg").hidden=true;return true}
const $=x=>document.getElementById(x);let range=null;
function remember(){const s=getSelection();if(s&&s.rangeCount)range=s.getRangeAt(0).cloneRange()}
function restore(){const s=getSelection();if(range){try{s.removeAllRanges();s.addRange(range)}catch{}}}
function normalizeEditorFonts(){const root=$("content");if(!root)return;root.querySelectorAll("font").forEach(f=>{const size=f.getAttribute("size");if(size&&!f.className)f.className="editor-font-size-"+size;f.removeAttribute("face")})}
$("content")?.addEventListener("mouseup",remember);$("content")?.addEventListener("keyup",remember);
document.querySelectorAll(".toolbar").forEach(tb=>{
 tb.addEventListener("pointerdown",e=>{if(e.target.closest("button")||e.target.matches("select"))remember()});
 tb.addEventListener("mousedown",e=>{if(e.target.closest("button"))e.preventDefault()});
 tb.querySelectorAll("button[data-cmd]").forEach(b=>b.onclick=()=>{const e=$(tb.dataset.target);restore();e.focus();document.execCommand(b.dataset.cmd,false,b.dataset.value||null);normalizeEditorFonts();remember()});
});
document.querySelectorAll("[data-font]").forEach(sel=>sel.onchange=()=>{const e=$(sel.dataset.font);restore();e.focus();if(sel.value)document.execCommand("fontName",false,sel.value);normalizeEditorFonts();remember()});
document.querySelectorAll("[data-size]").forEach(sel=>sel.onchange=()=>{const e=$(sel.dataset.size);restore();e.focus();document.execCommand("fontSize",false,sel.value||"3");normalizeEditorFonts();remember()});
$("insertMarker")?.addEventListener("click",()=>{restore();document.execCommand("insertText",false,"~");remember()});
function wrap(cls){restore();const s=getSelection();if(!s.rangeCount||s.isCollapsed)return;const r=s.getRangeAt(0);const sp=document.createElement("span");sp.className=cls;sp.appendChild(r.extractContents());r.insertNode(sp);remember()}
$("makeSanskrit")?.addEventListener("click",()=>wrap("sanskrit-text"));$("makeHindi")?.addEventListener("click",()=>wrap("hindi-text"));
$("anushtubh")?.addEventListener("click",()=>{restore();const s=getSelection();if(!s.rangeCount||s.isCollapsed){alert("चार पाद select करें।");return}const r=s.getRangeAt(0),text=r.cloneContents().textContent||"",lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean);if(lines.length!==4){alert("अनुष्टुप् के लिए चार पाद अलग-अलग line में रखें और select करें।");return}const box=document.createElement("div");box.className="sanskrit-text";box.dataset.chhand="anushtubh";box.innerHTML=lines.map((x,i)=>`<div data-pada="${i+1}" class="${i===0||i===3?"tone-a":"tone-b"}">${x}</div>`).join("");r.deleteContents();r.insertNode(box);remember()});
$("logout")?.addEventListener("click",async()=>{await fetch("/api/admin/logout",{method:"POST",credentials:"include"});location.replace("/admin/login.html")});
async function load(){const r=await fetch("/api/chapters",{cache:"no-store"}),a=await r.json();$("items").innerHTML=Array.isArray(a)&&a.length?a.map(x=>`<div class="status"><b>${x.chapter_number||""}. ${x.title}</b> <button onclick="edit('${x.id}')">Edit</button></div>`).join(""):"कोई प्रकाशित सामग्री नहीं"}
window.edit=async id=>{const x=await fetch("/api/chapter?id="+encodeURIComponent(id),{cache:"no-store"}).then(r=>r.json());$("id").value=x.id;$("num").value=x.chapter_number||"";$("title").value=x.title||"";$("slug").value=x.slug||"";$("sub").value=x.subtitle||"";$("imageUrl").value=x.image_url||"";$("contentType").value=x.content_type||"content";$("seoTitle").value=x.seo_title||"";$("seoDesc").value=x.seo_description||"";$("content").innerHTML=x.content_html||"";scrollTo(0,0)};
$("save").onclick=async()=>{normalizeEditorFonts();const p={id:$("id").value||crypto.randomUUID(),chapter_number:Number($("num").value||0),title:$("title").value.trim(),slug:$("slug").value.trim(),subtitle:$("sub").value.trim(),image_url:$("imageUrl").value.trim(),content_type:$("contentType").value,content_html:$("content").innerHTML,seo_title:$("seoTitle").value.trim(),seo_description:$("seoDesc").value.trim(),status:"published"};if(!p.title){$("msg").textContent="✕ शीर्षक जरूरी है।";return}const r=await fetch("/api/chapter",{method:"POST",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify(p)}),x=await r.json().catch(()=>({}));$("msg").textContent=r.ok?"✓ Published":"✕ "+(x.error||"Save failed");if(r.ok)load()};
$("new")?.addEventListener("click",()=>location.reload());$("content")?.addEventListener("paste",()=>setTimeout(normalizeEditorFonts,0));auth().then(ok=>ok&&load());
