const API="https://durga-saptashati.roshanchoudhary.workers.dev";
async function auth(){const r=await fetch(API+"/api/admin/me",{credentials:"include",cache:"no-store"});if(!r.ok){location.replace("/admin/login.html");return false}document.getElementById("panel").hidden=false;document.getElementById("authMsg").hidden=true;return true}
document.getElementById("logout")?.addEventListener("click",async()=>{await fetch(API+"/api/admin/logout",{method:"POST",credentials:"include"});location.replace("/admin/login.html")});
const $=x=>document.getElementById(x);let editing=null;
document.querySelectorAll(".toolbar").forEach(tb=>{tb.addEventListener("mousedown",e=>{if(e.target.closest("button"))e.preventDefault()});tb.querySelectorAll("button").forEach(b=>b.onclick=()=>{const ed=$(tb.dataset.target);ed.focus();document.execCommand(b.dataset.cmd,false,b.dataset.value||null)})});
document.querySelectorAll("[data-font]").forEach(s=>s.onchange=()=>{if(s.value){$(s.dataset.font).focus();document.execCommand('fontName',false,s.value)}});
document.querySelectorAll("[data-size]").forEach(s=>s.onchange=()=>{if(s.value){$(s.dataset.size).focus();document.execCommand("fontSize",false,s.value)}});
async function load(){const r=await fetch(API+"/api/chapters");const a=await r.json();$("items").innerHTML=a.map(x=>`<div class="status"><b>${x.chapter_number}. ${x.title}</b> <button onclick="edit('${x.id}')">Edit</button></div>`).join("")||"कोई published chapter नहीं";}
window.edit=async id=>{const x=await fetch(API+"/api/chapter?id="+encodeURIComponent(id)).then(r=>r.json());editing=id;$("id").value=x.id;$("num").value=x.chapter_number;$("title").value=x.title;$("sub").value=x.subtitle||"";$("seoTitle").value=x.seo_title||"";$("seoDesc").value=x.seo_description||"";$("content").innerHTML=x.content_html||"";scrollTo(0,0)};
$("save").onclick=async()=>{const p={id:$("id").value||crypto.randomUUID(),chapter_number:Number($("num").value),title:$("title").value.trim(),subtitle:$("sub").value.trim(),content_html:$("content").innerHTML,seo_title:$("seoTitle").value.trim(),seo_description:$("seoDesc").value.trim(),status:"published"};if(!p.chapter_number||!p.title){$("msg").textContent="क्रमांक और नाम जरूरी है।";return}const r=await fetch(API+"/api/chapter",{method:"POST",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify(p)});$("msg").textContent=r.ok?"✓ Published":"✕ Save failed";load()};
$("new").onclick=()=>location.reload();auth().then(ok=>ok&&load());
